/** Human-readable labels for extracted field keys. */
export const FIELD_LABELS: Record<string, string> = {
  date: "Date",
  architectName: "Architect Name",
  address: "Address",
  ctsNumber: "CTS Number",
  area: "Area",
  propertyIdentifier: "Property Identifier",
  ward: "Ward",
  proposalNumber: "Proposal Number",
  directorName: "Director Name",
  coaRegistrationNumber: "COA Registration Number",
  coaValidUpto: "COA Valid Upto",
  ccTo: "C. C. to",
  panNumber: "PAN Number",
  name: "Name",
  fatherName: "Father's Name",
  dateOfBirth: "Date of Birth",
  signature: "Signature",
  qrCode: "QR Code",
  certificateNumber: "Certificate Number",
  coaCertificateNumber: "COA Certificate Number",
  coaLicenseExpiryDate: "COA License Expiry Date",
  approvalDate: "Approval Date",
  validityDate: "Validity Date",
  technicalPersonName: "Technical Person Name",
  organizationName: "Organization Name",
  applicationDate: "Application Date",
  profession: "Profession",
  regulationNumber: "Regulation Number",
  state: "State",
  signatoryName: "Signatory Name",
  signatoryDesignation: "Signatory Designation",
  department: "Department",
  officeLocation: "Office Location",
  enrollmentNumber: "Enrollment Number",
  contactNumber: "Contact Number",
  issueDate: "Issue Date",
  referenceNumber: "Reference Number",
  documentId: "Document ID",
  aadhaarNumber: "Aadhaar Number",
  aadhaarNo: "Aadhaar Number",
  city: "City",
  pincode: "Pincode",
  consultantType: "Consultant Type",
  alternatePhone: "Phone Number",
  vid: "VID",
  yearOfBirth: "Year of Birth",
  "Date of Birth / Year of Birth": "Date of Birth / Year of Birth",
  gender: "Gender",
  signatureStatus: "Signature Status",
  photo: "Photo",
  barcode: "Barcode",
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  pan: "PAN",
  aadhaarCardFile: "Aadhaar Card",
  panCardFile: "PAN Card",
  licenseCertificateFile: "Technical Person License",
  addressLine1: "Address Line 1",
  addressLine2: "Address Line 2",
  addressLine3: "Address Line 3",
  residentialAddress: "Residential Address",
  entityName: "Entity Name",
  fullNameProprietor: "Full Name of Proprietor",
  registrationDate: "Registration Date",
  ownerName: "Owner Name",
  plotName: "Plot Name",
  villageName: "Village Name",
  propertyAddress: "Property Address",
  landmark: "Landmark",
  proposedCtsNumber: "CTS Number(s)",
  grossPlotArea: "Gross Plot Area",
  planningAuthority: "Planning Authority",
  region: "Region",
  zone: "Zone",
  extractsJson: "CTS Extract Rows",
  roadName: "Road Name",
  dpZone: "DP Zone",
  crzCategory: "CRZ Category",
  fullNameOfApplicant: "Full Name of Applicant",
  addressOfApplicant: "Address of Applicant",
  applicantType: "Applicant Type",
  applicantName: "Applicant Name",
  applicantAddress: "Applicant Address",
  panNo: "PAN",
  principalName: "Principal Name",
  attorneyName: "Attorney Name",
};

export function getFieldLabel(key: string): string {
  return FIELD_LABELS[key] ?? key;
}
